### ISSUE TITLE
`data/wbm/compile_wbm_test_set.py`: various errors

### ISSUE THREAD

**Issue by pbenner** [janosh/matbench-discovery#121]
I've attached a [patch](https://github.com/user-attachments/files/16494671/wbm-compile-data.txt) that fixes most issues for me. However, two asserts fail:
```py
assert n_corrected == 100_930, f"{n_corrected=} expected 100,930"
assert df_summary.e_correction_per_atom_mp2020.mean().round(4) == -0.1069
```

Also I get:
```py
Traceback (most recent call last):
  File "/home/pbenner/.local/opt/anaconda3/envs/mace/lib/python3.11/site-packages/pymatgen/analysis/phase_diagram.py", line 1776, in get_decomposition
    pd = self.get_pd_for_entry(comp)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pbenner/.local/opt/anaconda3/envs/mace/lib/python3.11/site-packages/pymatgen/analysis/phase_diagram.py", line 1763, in get_pd_for_entry
    raise ValueError(f"No suitable PhaseDiagrams found for {entry}.")
ValueError: No suitable PhaseDiagrams found for Ac6 U2.
```

And:
```py
  File "/home/pbenner/.local/opt/anaconda3/envs/mace/lib/python3.11/site-packages/pymatgen/analysis/phase_diagram.py", line 1782, in get_decomposition
    return _get_slsqp_decomp(comp, competing_entries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pbenner/.local/opt/anaconda3/envs/mace/lib/python3.11/site-packages/pymatgen/analysis/phase_diagram.py", line 2088, in _get_slsqp_decomp
    Es = np.array([comp_entry.energy_per_atom for comp_entry in competing_entries])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pbenner/.local/opt/anaconda3/envs/mace/lib/python3.11/site-packages/pymatgen/analysis/phase_diagram.py", line 2088, in <listcomp>
    Es = np.array([comp_entry.energy_per_atom for comp_entry in competing_entries])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pbenner/.local/opt/anaconda3/envs/mace/lib/python3.11/site-packages/pymatgen/entries/__init__.py", line 87, in energy_per_atom
    return self.energy / self.composition.num_atoms
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pbenner/.local/opt/anaconda3/envs/mace/lib/python3.11/site-packages/pymatgen/core/composition.py", line 497, in num_atoms
    return self._n_atoms
           ^^^^^^^^^^^^^
AttributeError: 'Composition' object has no attribute '_n_atoms'. Did you mean: '_natoms'?
```

```sh
> pip list | grep pymatgen
pymatgen                  2024.7.18
```

**Comment by janosh** [comment]
thanks for reporting @pbenner. that script is surprisingly high-entropy, stuff keeps breaking. that `_n_atoms` error in particular is strange. i'll rerun your patch in a bit to see which errors i can reproduce.
